### ISSUE TITLE
Exit issue

### ISSUE THREAD

**Issue by LadyKira** [Sapein/Battle-Program-1#1]
When I type 2 to exit, it doesn't exit. When I typed "exit" it kept on telling me I attacked..

**Comment by Sapein** [comment]
You have to type exit (exactly like that) to exit.

**Comment by LadyKira** [comment]
When I typed "exit" it kept on telling me I attacked..

**Comment by Sapein** [comment]
Alright now that's a bug, I'll attempt to fix it

**Comment by Sapein** [comment]
Should be fixed
